
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerdemos'
        repository: 'ricafortdocker/products-store-mvc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'v2.$(Build.BuildId)'
