# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        containerRegistry: 'dockerdemos'
        repository: 'ricafortdocker/products-store-mvc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'v2.$(Build.BuildId)'
    - task: CopyFiles@2
      displayName: Copy kubernetes files
      inputs:
        Contents: |
          mssql-config-map.yaml
          mssql-deployment.yaml
          mssql-pv-az.yaml
          mssql-secret.yaml
          mvc-deployment-az.yaml
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        