kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
     name: aws-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  #storageaccounttype: gp2
  #kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-pv-claim
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  storageClassName: aws-ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi