---
apiVersion: extensions/v1beta1 #networking.k8s.io/v1beta1 #networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvc-ingress-host
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  
spec:
  tls:
    - secretName: letsencrypt-staging-products #products-ricafortdemos-local-tls
      hosts:
       - products.ricafort.net
  rules:
  - host: products.ricafort.net
    http:
      paths:
      #- pathType: Prefix
      #  path: "/bar"
        #- backend:
        #    serviceName: mvc-service
        #    servicePort: 80
        #  path: /mvc-service(/|$)(.*)
        - backend:
            serviceName: mvc-service
            servicePort: 80
          path: /(.*)
        - backend:
            serviceName: mvc-service
            servicePort: 80
          path: /(Delete.*)
        - backend:
            serviceName: mvc-service
            servicePort: 80
          path: /(Edit.*)
        - backend:
            serviceName: mvc-service
            servicePort: 80
          path: /(Create.*)
          #service:
          #  name: mvc-service
          #  port:
          #    number: 80